// Romantic
IF
Global("O#LynnAerieRomantic","GLOBAL",1)
InParty(Myself)
See(Player1)
!See("O#Lynn")
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END

// Sex
IF
Global("O#LynnAerieSex","GLOBAL",1)
InParty(Myself)
See(Player1)
!See("O#Lynn")
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END
