// Romantic
IF
Global("O#LynnViconiaRomantic","GLOBAL",1)
InParty(Myself)
See(Player1)
!See("O#Lynn")
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END

// Sex
IF
Global("O#LynnViconiaSex","GLOBAL",1)
InParty(Myself)
See(Player1)
!See("O#Lynn")
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END
